# log configures the logger
log:
  # level sets the log level, supports "panic", "fatal", "error", "warn", "info" and "debug". Defaults to "info".
  level: debug


# The port to listen on (defaults to 8080)
port: 8080
# The interface to listen and handle requests on (defaults to 127.0.0.1)
host: 127.0.0.1

# tls configures HTTPs (HTTP over TLS)
tls:
  # Key configures the private key (pem encoded)
  #key: ./key.pem
  # Cert configures the certificate (pem encoded)
  #cert: ./cert.pem
  # Configures the trust store (CA certificates to trust)
  #trust_store: ./ca_chain.pem

# Where the root home document is located to resolve required dependencies
# to the hydra admin service, the registration service and the authentication service
root_home_url: https://127.0.0.1:8092

# The following config entries will be removed as soon as usage of root home documents
# is supported

# Where the hydra admin service is located
hydra_admin_url: https://127.0.0.1:4445

# Where to send the user for registration purposes
register_url: http://127.0.0.1:8091/register

# Where to verify the credentials provided by the user
authenticate_url: http://127.0.0.1:8090/authenticate

